[breaking] Replace attached_policies_arns in aws_iam_role with map (#276)
## Summary
This is a resubmission of https://github.com/chanzuckerberg/cztack/pull/274. I tried to incorporate some feedback about making it backwards compatible, but that didn't work. I didn't notice that my TF plan completed unsuccessfully, hence me merging a bit too early. This PR reverts that and submits the change as we discussed. 

Sorry for the extra review request! 


#### Original Summary:
In situations where you were appending new resources to attached_policies_arns that didn't exist yet, Terraform would throw the following error:
```
Error: Invalid for_each argument

  on .terraform/modules/aws-role-devserver-restart/aws-iam-role/main.tf line 41, in resource "aws_iam_role_policy_attachment" "policy_attachment":
  41:   for_each   = toset(var.attached_policies_arns)

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```
This PR replaces the list with a map so that Terraform can get the size statically during the plan.


### Test Plan
Tested in the original PR

### References
(Optional) Additional links to provide more context.