[fix] Convert attached_policies_arns into a map within the aws_iam_role module (#274)
### Summary
In situations where you were appending new resources to `attached_policies_arns` that didn't exist yet, Terraform would throw the following error:
```
Error: Invalid for_each argument

  on .terraform/modules/aws-role-devserver-restart/aws-iam-role/main.tf line 41, in resource "aws_iam_role_policy_attachment" "policy_attachment":
  41:   for_each   = toset(var.attached_policies_arns)

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```
This PR replaces the list with a map so that Terraform can get the size statically during the plan. 

### Test Plan
Updating the consuming module in https://github.com/FB-PLP/terraform-infra-management/pull/900 and TF plan ([here](https://si.prod.tfe.czi.technology/app/lp-infra/accounts-summitps/runs/run-6pFATci8iJu1V6fh)) seems as expected 

### References
(Optional) Additional links to provide more context.